pipeline:
  name: IDP-Test
  identifier: IDPTest
  projectIdentifier: Terraform
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo <+stage.variables.name>
        variables:
          - name: name
            type: String
            description: ""
            required: true
            value: <+input>
          - name: Project
            type: String
            description: ""
            required: true
            value: <+input>
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Http_1
                  identifier: Http_1
                  spec:
                    url: https://www.deluxe.com
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                    requestBody: test
                  timeout: 10s
        tags: {}
        variables:
          - name: Account
            type: String
            description: ""
            required: true
            value: <+input>
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1697453905706
        repoName: Thomaspradeep/IDP
        build: <+input>
