pipeline:
  name: IDP-Test
  identifier: IDPTest
  projectIdentifier: Terraform
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo <+stage.variables.name>
        variables:
          - name: name
            type: String
            description: ""
            required: false
            value: Harness
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1697453905706
        repoName: Thomaspradeep/IDP
        build: <+input>
